### PR TITLE
added Gantt chart month format option

### PR DESCRIPTION
**Pull request by yasamoka**
Hello, this is in reference to https://github.com/Neoteroi/mkdocs-plugins/pull/57.

Thank you!

### CODE REVIEW

**Comment by yasamoka** [comment]
Hello, may you kindly merge this simple change so that it doesn't go stale eventually?

**Comment by RobertoPrevato** [comment]
Hi @yasamoka 
Sure, sorry I had an intense week at work and didn't have much time for projects in GitHub. :)

**Comment by yasamoka** [comment]
No worries, just thought you had missed it. Thanks!

**Comment by RobertoPrevato** [comment]
Thank You! Your contribution is in the docs site https://www.neoteroi.dev/mkdocs-plugins/gantt/#options

**Pull request merged**
